sudo: false
language: python

python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"


install:
    - pip install -r requirements.txt
    - python setup.py -q install

script:
    - py.test

branches:
  except:
    - website

notifications:
  email: false
